---
# defaults file for openmicroscopy.postgresql

# Version of postgres (see vars)
postgresql_version: "11"

# Whether to install and setup PostgreSQL server
postgresql_install_server: true

# Install contrib extensions?
postgresql_install_extensions: false

# List of dictionaries of databases
postgresql_databases: []

# List of dictionaries of users
postgresql_users: []

# Network interfaces to listen on
postgresql_server_listen: localhost

# Dictionary of additional postgresql.conf options
postgresql_server_conf: {}

# Whether to enable the default local authentication methods
postgresql_server_auth_local: true

# List of dictionaries of client authorisation lines
postgresql_server_auth: []

# Recursively reset the owner/group of the postgres datadir?
postgresql_server_chown_datadir: false





postgresql_external:
  repourl:
    "9.4": "https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-7-x86_64/pgdg-redhat94-9.4-3.noarch.rpm"
    "9.5": "https://download.postgresql.org/pub/repos/yum/9.5/redhat/rhel-7-x86_64/pgdg-redhat95-9.5-3.noarch.rpm"
    "9.6": "https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm"
    "10": "https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat10-10-2.noarch.rpm"
    "11": "https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm"
  basename:
    "9.4": postgresql94
    "9.5": postgresql95
    "9.6": postgresql96
    "10": postgresql10
    "11": postgresql11
  setup:
    "9.4": postgresql94-setup
    "9.5": postgresql95-setup
    "9.6": postgresql96-setup
    "10": postgresql-10-setup
    "11": postgresql-11-setup

# Internal role variables, do not modify
postgresql_bindir: /usr/pgsql-{{ postgresql_version }}/bin
postgresql_datadir: /var/lib/pgsql/{{ postgresql_version }}/data
postgresql_basename: "{{ postgresql_external.basename[postgresql_version] }}"
postgresql_repourl: "{{ postgresql_external.repourl[postgresql_version] }}"
postgresql_setupname: "{{ postgresql_external.setup[postgresql_version] }}"

