---
# Check the alt python3 version

    
- name: Ensure dependencies are installed
  yum: name={{ item }} state=present
  with_items:
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - readline-devel
    - pcre-devel
    - curl-devel
    
    
    
    
- name: Check if python is already installed
  stat: path=/usr/local/bin/python3.6
  register: python        
    


- name: Download Python
  get_url: url=https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tgz 
           dest=/tmp/Python-3.6.4.tgz
  when: not python.stat.exists    
  
  
  
- name: Unpack Python
  unarchive: src=/tmp/Python-3.6.4.tgz dest=/tmp copy=no
  when: not python.stat.exists

- name: Configure, compile and install Python
  shell: cd /tmp/Python-3.6.4 && {{ item }}
  with_items:
    - ./configure
    - make
    - make altinstall
  when: not python.stat.exists  
    
